on:
  pull_request:
    branches: main
  workflow_dispatch:

name: pr_check

jobs:
  bookdown:
    name: pr_check_book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with: 
          r-version: '4.0.5'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-6-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-6-

      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
        shell: Rscript {0}

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
